//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRoam.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduRoam.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported CLI commands:
        ///
        ///    /? : 
        ///            Show this help text
        ///    /help : 
        ///            Show this help text
        ///    /install : 
        ///            Install this binary to %USER%/AppData/Local
        ///    /uninstall : 
        ///            Uninstall this binary from %USER%/AppData/Local along
        ///            with any configured data
        ///    /background : 
        ///            Start this application hidden to the tray
        ///            (works only if run from install directory)
        ///    /close : 
        ///            Close the current running instance
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AppCommandsHelp {
            get {
                return ResourceManager.GetString("AppCommandsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eduroam.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ButtonConnect {
            get {
                return ResourceManager.GetString("ButtonConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string ButtonInstall {
            get {
                return ResourceManager.GetString("ButtonInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string ButtonPrevious {
            get {
                return ResourceManager.GetString("ButtonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate:.
        /// </summary>
        public static string CertificateLabel {
            get {
                return ResourceManager.GetString("CertificateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to continue the following certificates have to be installed..
        /// </summary>
        public static string CertificatesInstallationNotification {
            get {
                return ResourceManager.GetString("CertificatesInstallationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, installed: {1}.
        /// </summary>
        public static string CertificatesInstallationStatus {
            get {
                return ResourceManager.GetString("CertificatesInstallationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to certificates are installed.
        /// </summary>
        public static string CertificateTitleInstalled {
            get {
                return ResourceManager.GetString("CertificateTitleInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to continue you have to install the listed certificates.
        /// </summary>
        public static string CertificateTitleStart {
            get {
                return ResourceManager.GetString("CertificateTitleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Wi-Fi based on a institution profile and connect..
        /// </summary>
        public static string CommandDescriptionConnect {
            get {
                return ResourceManager.GetString("CommandDescriptionConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install this binary to %USER%/AppData/Local.
        /// </summary>
        public static string CommandDescriptionInstall {
            get {
                return ResourceManager.GetString("CommandDescriptionInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a list of institutions or profiles for a institution..
        /// </summary>
        public static string CommandDescriptionList {
            get {
                return ResourceManager.GetString("CommandDescriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reauthenticate.
        /// </summary>
        public static string CommandDescriptionReauthenticate {
            get {
                return ResourceManager.GetString("CommandDescriptionReauthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh credentials.
        /// </summary>
        public static string CommandDescriptionRefresh {
            get {
                return ResourceManager.GetString("CommandDescriptionRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove configured Wi-Fi profile and/or root certificates.
        /// </summary>
        public static string CommandDescriptionRemove {
            get {
                return ResourceManager.GetString("CommandDescriptionRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show EAP Config information.
        /// </summary>
        public static string CommandDescriptionShow {
            get {
                return ResourceManager.GetString("CommandDescriptionShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show status.
        /// </summary>
        public static string CommandDescriptionStatus {
            get {
                return ResourceManager.GetString("CommandDescriptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall application.
        /// </summary>
        public static string CommandDescriptionUninstall {
            get {
                return ResourceManager.GetString("CommandDescriptionUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is configured!
        ///Could not connect because no EAP Config could be found.
        /// </summary>
        public static string ConfiguredButNotConnected {
            get {
                return ResourceManager.GetString("ConfiguredButNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is configured!
        ///Unable to connect to eduroam, you&apos;re probably out of coverage..
        /// </summary>
        public static string ConfiguredButProbablyOutOfCoverage {
            get {
                return ResourceManager.GetString("ConfiguredButProbablyOutOfCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is configured!
        ///Unable to connect to eduroam..
        /// </summary>
        public static string ConfiguredButUnableToConnect {
            get {
                return ResourceManager.GetString("ConfiguredButUnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAP is configured.
        /// </summary>
        public static string ConfiguredEap {
            get {
                return ResourceManager.GetString("ConfiguredEap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now connected to EduRoam..
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a username and password to connect..
        /// </summary>
        public static string ConnectionUsernameAndPasswordRequired {
            get {
                return ResourceManager.GetString("ConnectionUsernameAndPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string ConsentMain {
            get {
                return ResourceManager.GetString("ConsentMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the institution.
        /// </summary>
        public static string ConsentPost {
            get {
                return ResourceManager.GetString("ConsentPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &apos;Next&apos; you agree to the.
        /// </summary>
        public static string ConsentPre {
            get {
                return ResourceManager.GetString("ConsentPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username and password.
        /// </summary>
        public static string CredentialsLabel {
            get {
                return ResourceManager.GetString("CredentialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string CredentialsPasswordLabel {
            get {
                return ResourceManager.GetString("CredentialsPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string CredentialsUsernameLabel {
            get {
                return ResourceManager.GetString("CredentialsUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more days.
        /// </summary>
        public static string DaysLeft {
            get {
                return ResourceManager.GetString("DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geteduroam.
        /// </summary>
        public static string DefaultIdentityProvider {
            get {
                return ResourceManager.GetString("DefaultIdentityProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API error.
        /// </summary>
        public static string ErrorApi {
            get {
                return ResourceManager.GetString("ErrorApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t connect to the server.
        ///
        ///Make sure that you are connected to the internet, then try again.
        ///
        ///Exception: {0}.
        /// </summary>
        public static string ErrorCannotConnectWithServer {
            get {
                return ResourceManager.GetString("ErrorCannotConnectWithServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t fetch token json.
        ///Exception: {0}.
        /// </summary>
        public static string ErrorCannotFetchTokens {
            get {
                return ResourceManager.GetString("ErrorCannotFetchTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some WLAN profile could not be removed.
        /// </summary>
        public static string ErrorCannotRemoveWLANProfile {
            get {
                return ResourceManager.GetString("ErrorCannotRemoveWLANProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve profile when offline.
        /// </summary>
        public static string ErrorCannotRetrieveProfileWhenOffline {
            get {
                return ResourceManager.GetString("ErrorCannotRetrieveProfileWhenOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client credential is not valid yet.
        /// </summary>
        public static string ErrorClientCredentialNotValidYes {
            get {
                return ResourceManager.GetString("ErrorClientCredentialNotValidYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is configured!
        ///Could not connect because EAP Config could no be found.
        /// </summary>
        public static string ErrorConfiguredButNotConnected {
            get {
                return ResourceManager.GetString("ErrorConfiguredButNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is configured!
        ///Unable to connect to eduroam, you&apos;re probably out of coverage..
        /// </summary>
        public static string ErrorConfiguredButProbablyOutOfCoverage {
            get {
                return ResourceManager.GetString("ErrorConfiguredButProbablyOutOfCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is configured!
        ///Unable to connect to eduroam..
        /// </summary>
        public static string ErrorConfiguredButUnableToConnect {
            get {
                return ResourceManager.GetString("ErrorConfiguredButUnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must contain @ exactly once.
        /// </summary>
        public static string ErrorCredentialsAtChar {
            get {
                return ResourceManager.GetString("ErrorCredentialsAtChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot end with a period or whitespace.
        /// </summary>
        public static string ErrorCredentialsEndsWith {
            get {
                return ResourceManager.GetString("ErrorCredentialsEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must end with .{0} or @{0}.
        /// </summary>
        public static string ErrorCredentialsEndWithRealm {
            get {
                return ResourceManager.GetString("ErrorCredentialsEndWithRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must end with @{0}.
        /// </summary>
        public static string ErrorCredentialsEndWithRealmNoSubdomain {
            get {
                return ResourceManager.GetString("ErrorCredentialsEndWithRealmNoSubdomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters such as . and @ can not be adjacent to each other.
        /// </summary>
        public static string ErrorCredentialsSpecialCharacters {
            get {
                return ResourceManager.GetString("ErrorCredentialsSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected EAP config file is corrupted. Please choose another file..
        /// </summary>
        public static string ErrorEapConfigCorrupted {
            get {
                return ResourceManager.GetString("ErrorEapConfigCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read from file. Make sure to select a valid EAP config file..
        /// </summary>
        public static string ErrorEapConfigInvalid {
            get {
                return ResourceManager.GetString("ErrorEapConfigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect, EAP Configuration is empty.
        /// </summary>
        public static string ErrorEapConfigIsEmpty {
            get {
                return ResourceManager.GetString("ErrorEapConfigIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAP could not be configured.
        /// </summary>
        public static string ErrorEapNotConfigured {
            get {
                return ResourceManager.GetString("ErrorEapNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error with internet connection.
        /// </summary>
        public static string ErrorInternetConnection {
            get {
                return ResourceManager.GetString("ErrorInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid certificate path.
        /// </summary>
        public static string ErrorInvalidCertificatePath {
            get {
                return ResourceManager.GetString("ErrorInvalidCertificatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and/or password are not valid.
        /// </summary>
        public static string ErrorInvalidCredentials {
            get {
                return ResourceManager.GetString("ErrorInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid eap config provided, this should not happen, please report a bug..
        /// </summary>
        public static string ErrorInvalidEapConfig {
            get {
                return ResourceManager.GetString("ErrorInvalidEapConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials are not provided.
        /// </summary>
        public static string ErrorMissingCredentials {
            get {
                return ResourceManager.GetString("ErrorMissingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required CA certificate was not installed, this should not happen, please report a bug.
        /// </summary>
        public static string ErrorMissingRequiredCACertificate {
            get {
                return ResourceManager.GetString("ErrorMissingRequiredCACertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No (valid) client certificate was provided ({0} parameter..
        /// </summary>
        public static string ErrorNoClientCertificateProvided {
            get {
                return ResourceManager.GetString("ErrorNoClientCertificateProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect. 
        ///Exception: {0}..
        /// </summary>
        public static string ErrorNoConnection {
            get {
                return ResourceManager.GetString("ErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        public static string ErrorNoInternet {
            get {
                return ResourceManager.GetString("ErrorNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geteduroam has not been uninstalled..
        /// </summary>
        public static string ErrorNotUninstalled {
            get {
                return ResourceManager.GetString("ErrorNotUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} option value cannot be empty or whitespace only.
        /// </summary>
        public static string ErrorOptionIsEmpty {
            get {
                return ResourceManager.GetString("ErrorOptionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required certificates are installed..
        /// </summary>
        public static string ErrorRequiredCertificatesNotInstalled {
            get {
                return ResourceManager.GetString("ErrorRequiredCertificatesNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing options. Provide the {0} option or both {1} and {2} options.
        /// </summary>
        public static string ErrorShowCommandOptions {
            get {
                return ResourceManager.GetString("ErrorShowCommandOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown profile.
        /// </summary>
        public static string ErrorUnknownProfile {
            get {
                return ResourceManager.GetString("ErrorUnknownProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection of type {0} is not supported (yet)..
        /// </summary>
        public static string ErrorUnsupportedConnectionType {
            get {
                return ResourceManager.GetString("ErrorUnsupportedConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The institution or profile is either not supported or malformed.
        ///Please select a different institution or profile.
        ///
        ///Exception: {0}.
        /// </summary>
        public static string ErrorUnsupportedInstituteOrProfile {
            get {
                return ResourceManager.GetString("ErrorUnsupportedInstituteOrProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile you have selected is not supported by this application. No supported authentification method was found..
        /// </summary>
        public static string ErrorUnsupportedProfile {
            get {
                return ResourceManager.GetString("ErrorUnsupportedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless is unavailable on this computer.
        /// </summary>
        public static string ErrorWirelessUnavailable {
            get {
                return ResourceManager.GetString("ErrorWirelessUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file..
        /// </summary>
        public static string FileDialogSelectFile {
            get {
                return ResourceManager.GetString("FileDialogSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more hours.
        /// </summary>
        public static string HoursLeft {
            get {
                return ResourceManager.GetString("HoursLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string IsSure {
            get {
                return ResourceManager.GetString("IsSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is valid for.
        /// </summary>
        public static string LabelAccountValidFor {
            get {
                return ResourceManager.GetString("LabelAccountValidFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string LabelHelp {
            get {
                return ResourceManager.GetString("LabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string LabelProfile {
            get {
                return ResourceManager.GetString("LabelProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported.
        /// </summary>
        public static string LabelSupported {
            get {
                return ResourceManager.GetString("LabelSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string LabelTermsOfUse {
            get {
                return ResourceManager.GetString("LabelTermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version.
        /// </summary>
        public static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string LabelWeb {
            get {
                return ResourceManager.GetString("LabelWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Client Certificate bundle.
        /// </summary>
        public static string LoadCertificateFile {
            get {
                return ResourceManager.GetString("LoadCertificateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a EAP Config file.
        /// </summary>
        public static string LoadEapFile {
            get {
                return ResourceManager.GetString("LoadEapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This profile requires a local certificate.
        /// </summary>
        public static string LocalCertificateLabel {
            get {
                return ResourceManager.GetString("LocalCertificateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load .eap-config file....
        /// </summary>
        public static string MenuItemLoadEAP {
            get {
                return ResourceManager.GetString("MenuItemLoadEAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reauthenticate....
        /// </summary>
        public static string MenuItemReauthenticate {
            get {
                return ResourceManager.GetString("MenuItemReauthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh credential.
        /// </summary>
        public static string MenuItemRefresh {
            get {
                return ResourceManager.GetString("MenuItemRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove root certificates....
        /// </summary>
        public static string MenuItemRemoveCertificates {
            get {
                return ResourceManager.GetString("MenuItemRemoveCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove configured Wi-Fi profile....
        /// </summary>
        public static string MenuItemRemoveProfile {
            get {
                return ResourceManager.GetString("MenuItemRemoveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall application....
        /// </summary>
        public static string MenuItemUninstall {
            get {
                return ResourceManager.GetString("MenuItemUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more minutes.
        /// </summary>
        public static string MinutesLeft {
            get {
                return ResourceManager.GetString("MinutesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No EAP Config info to show.
        /// </summary>
        public static string NoEAPConfig {
            get {
                return ResourceManager.GetString("NoEAPConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        public static string NotSure {
            get {
                return ResourceManager.GetString("NotSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue you need to authenticate in your browser, a window should have opened automatically..
        /// </summary>
        public static string OAuthExplanation {
            get {
                return ResourceManager.GetString("OAuthExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting ....
        /// </summary>
        public static string OAuthTitle {
            get {
                return ResourceManager.GetString("OAuthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate filepath.
        /// </summary>
        public static string OptionDescriptionCertificatePath {
            get {
                return ResourceManager.GetString("OptionDescriptionCertificatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to EAP config .eap-config..
        /// </summary>
        public static string OptionDescriptionEAPConfig {
            get {
                return ResourceManager.GetString("OptionDescriptionEAPConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force action..
        /// </summary>
        public static string OptionDescriptionForce {
            get {
                return ResourceManager.GetString("OptionDescriptionForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the institute to connect to..
        /// </summary>
        public static string OptionDescriptionInstitute {
            get {
                return ResourceManager.GetString("OptionDescriptionInstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute&apos;s profile to connect to..
        /// </summary>
        public static string OptionDescriptionProfile {
            get {
                return ResourceManager.GetString("OptionDescriptionProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query to filter items.
        /// </summary>
        public static string OptionDescriptionQuery {
            get {
                return ResourceManager.GetString("OptionDescriptionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option {0} is required.
        /// </summary>
        public static string OptionRequired {
            get {
                return ResourceManager.GetString("OptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate passphrase.
        /// </summary>
        public static string Passphrase {
            get {
                return ResourceManager.GetString("Passphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password for the certificate.
        /// </summary>
        public static string PassphraseLabel {
            get {
                return ResourceManager.GetString("PassphraseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ProfileContactInfo {
            get {
                return ResourceManager.GetString("ProfileContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ProfileEmail {
            get {
                return ResourceManager.GetString("ProfileEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not affiliated with institution?.
        /// </summary>
        public static string ProfileNotAffiliatedInstitution {
            get {
                return ResourceManager.GetString("ProfileNotAffiliatedInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ProfilePhone {
            get {
                return ResourceManager.GetString("ProfilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will remove all configuration for &apos;{0}&apos;..
        /// </summary>
        public static string ProfileRemoveConfirmation {
            get {
                return ResourceManager.GetString("ProfileRemoveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select another profile.
        /// </summary>
        public static string ProfileSelectOtherInstitution {
            get {
                return ResourceManager.GetString("ProfileSelectOtherInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string ProfileWeb {
            get {
                return ResourceManager.GetString("ProfileWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to be redirected to the insitutions site for more info on how to connect. When you click the link this application will close..
        /// </summary>
        public static string RedirectText {
            get {
                return ResourceManager.GetString("RedirectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect.
        /// </summary>
        public static string RedirectTitle {
            get {
                return ResourceManager.GetString("RedirectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will remove all configuration for
        ///{0}.
        /// </summary>
        public static string RemoveProfileMessage {
            get {
                return ResourceManager.GetString("RemoveProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0}.
        /// </summary>
        public static string RemoveProfileTitle {
            get {
                return ResourceManager.GetString("RemoveProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install all required certificates?.
        /// </summary>
        public static string RequestToInstallCertificates {
            get {
                return ResourceManager.GetString("RequestToInstallCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select institution.
        /// </summary>
        public static string SelectInstitution {
            get {
                return ResourceManager.GetString("SelectInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select profile.
        /// </summary>
        public static string SelectProfile {
            get {
                return ResourceManager.GetString("SelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string TermsOfUseTitle {
            get {
                return ResourceManager.GetString("TermsOfUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application and its configuration have been uninstalled..
        /// </summary>
        public static string UninstallNotification {
            get {
                return ResourceManager.GetString("UninstallNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall geteduroam.
        /// </summary>
        public static string UninstallNotificationTitle {
            get {
                return ResourceManager.GetString("UninstallNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @example.com.
        /// </summary>
        public static string UserNameWatermark {
            get {
                return ResourceManager.GetString("UserNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}+Debug.
        /// </summary>
        public static string VersionDebug {
            get {
                return ResourceManager.GetString("VersionDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string VersionDebugNoVersion {
            get {
                return ResourceManager.GetString("VersionDebugNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string VersionRelease {
            get {
                return ResourceManager.GetString("VersionRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versionless.
        /// </summary>
        public static string VersionReleaseNoVersion {
            get {
                return ResourceManager.GetString("VersionReleaseNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file does not exist..
        /// </summary>
        public static string WarningFileDoesNotExist {
            get {
                return ResourceManager.GetString("WarningFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first install certificates with InstallCertificates.
        /// </summary>
        public static string WarningInstallCertificates {
            get {
                return ResourceManager.GetString("WarningInstallCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing certificates.
        /// </summary>
        public static string WarningMissingCertificates {
            get {
                return ResourceManager.GetString("WarningMissingCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No institutes found.
        /// </summary>
        public static string WarningNoInstitutesFound {
            get {
                return ResourceManager.GetString("WarningNoInstitutesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles found.
        /// </summary>
        public static string WarningNoProfilesFound {
            get {
                return ResourceManager.GetString("WarningNoProfilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supported authentification method was found..
        /// </summary>
        public static string WarningNoSupportedAuthenticationMethod {
            get {
                return ResourceManager.GetString("WarningNoSupportedAuthenticationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile you have selected is not supported by this application..
        /// </summary>
        public static string WarningProfileNotSupported {
            get {
                return ResourceManager.GetString("WarningProfileNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently in the process of completly uninstalling geteduroam.
        /// </summary>
        public static string WarningUninstall {
            get {
                return ResourceManager.GetString("WarningUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This means uninstalling all the trusted root certificates installed by this application..
        /// </summary>
        public static string WarningUninstallCertificates {
            get {
                return ResourceManager.GetString("WarningUninstallCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type you chose is not supported..
        /// </summary>
        public static string WarningUnsupportedFileType {
            get {
                return ResourceManager.GetString("WarningUnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /!\ The realm for the OuterIdentity will be set to &quot;{0}&quot; but the profile specified &quot;{1}&quot;.
        /// </summary>
        public static string WarnRealmMismatch {
            get {
                return ResourceManager.GetString("WarnRealmMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
