// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Classes.CertificateGrid.btnInstall_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~P:WpfApp.SelfInstaller.rnsRun")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~P:WpfApp.SelfInstaller.rnsUninstall")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.MainWindow.btnBack_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.MainWindow.btnNext_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.MainWindow.tb_TrayLeftMouseDown(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.InstalledProfile.btnMainMenu_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.InstalledProfile.btnLogout_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.Login.btnCancelWait_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.Login.btnFile_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.Login.pbCertBrowserPassword_GotFocus(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.Login.pbCertBrowserPassword_PasswordChanged(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.Login.pbCertPassword_GotFocus(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.Login.pbCertPassword_PasswordChanged(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.Login.pbCredPassword_GotFocus(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.Login.pbCredPassword_PasswordChanged(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.Login.tbUsername_GotFocus(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.Login.tbUsername_LostFocus(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.Login.tbUsername_TextChanged(System.Object,System.Windows.Controls.TextChangedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~P:WpfApp.Menu.Login.dispatcherTimer")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "Autogenerated by Visual Studio", Scope = "member", Target = "~M:WpfApp.Menu.Login.dispatcherTimer_Tick(System.Object,System.EventArgs)")]
