//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRoam.Connect.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduRoam.Connect.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geteduroam CLI.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Wi-Fi based on a institution profile.
        /// </summary>
        public static string CommandDescriptionConfigure {
            get {
                return ResourceManager.GetString("CommandDescriptionConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with the current profile.
        /// </summary>
        public static string CommandDescriptionConnect {
            get {
                return ResourceManager.GetString("CommandDescriptionConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a list of institutions or profiles for a institution..
        /// </summary>
        public static string CommandDescriptionList {
            get {
                return ResourceManager.GetString("CommandDescriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reauthenticate.
        /// </summary>
        public static string CommandDescriptionReauthenticate {
            get {
                return ResourceManager.GetString("CommandDescriptionReauthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh credentials.
        /// </summary>
        public static string CommandDescriptionRefresh {
            get {
                return ResourceManager.GetString("CommandDescriptionRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove configured Wi-Fi profile and/or root certificates.
        /// </summary>
        public static string CommandDescriptionRemove {
            get {
                return ResourceManager.GetString("CommandDescriptionRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show EAP Config information.
        /// </summary>
        public static string CommandDescriptionShow {
            get {
                return ResourceManager.GetString("CommandDescriptionShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show status.
        /// </summary>
        public static string CommandDescriptionStatus {
            get {
                return ResourceManager.GetString("CommandDescriptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall application.
        /// </summary>
        public static string CommandDescriptionUninstall {
            get {
                return ResourceManager.GetString("CommandDescriptionUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is configured!\nCould not connect because no EAP Config could be found.
        /// </summary>
        public static string ConfiguredButNotConnected {
            get {
                return ResourceManager.GetString("ConfiguredButNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is configured!\nUnable to connect to eduroam, you&apos;re probably out of coverage..
        /// </summary>
        public static string ConfiguredButProbablyOutOfCoverage {
            get {
                return ResourceManager.GetString("ConfiguredButProbablyOutOfCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is configured!\nUnable to connect to eduroam..
        /// </summary>
        public static string ConfiguredButUnableToConnect {
            get {
                return ResourceManager.GetString("ConfiguredButUnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAP is configured.
        /// </summary>
        public static string ConfiguredEap {
            get {
                return ResourceManager.GetString("ConfiguredEap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now connected to EduRoam..
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more days.
        /// </summary>
        public static string DaysLeft {
            get {
                return ResourceManager.GetString("DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geteduroam.
        /// </summary>
        public static string DefaultIdentityProvider {
            get {
                return ResourceManager.GetString("DefaultIdentityProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API error.
        /// </summary>
        public static string ErrorApi {
            get {
                return ResourceManager.GetString("ErrorApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect, EAP Configuration is empty.
        /// </summary>
        public static string ErrorEapConfigIsEmpty {
            get {
                return ResourceManager.GetString("ErrorEapConfigIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAP could not be configured.
        /// </summary>
        public static string ErrorEapNotConfigured {
            get {
                return ResourceManager.GetString("ErrorEapNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect. \nException: {0}..
        /// </summary>
        public static string ErrorNoConnection {
            get {
                return ResourceManager.GetString("ErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        public static string ErrorNoInternet {
            get {
                return ResourceManager.GetString("ErrorNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geteduroam has not been uninstalled..
        /// </summary>
        public static string ErrorNotUninstalled {
            get {
                return ResourceManager.GetString("ErrorNotUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} option value cannot be empty or whitespace only.
        /// </summary>
        public static string ErrorOptionIsEmpty {
            get {
                return ResourceManager.GetString("ErrorOptionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing options. Provide the {0} option or both {1} and {2} options.
        /// </summary>
        public static string ErrorShowCommandOptions {
            get {
                return ResourceManager.GetString("ErrorShowCommandOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile you have selected is not supported by this application. No supported authentification method was found..
        /// </summary>
        public static string ErrorUnsupportedProfile {
            get {
                return ResourceManager.GetString("ErrorUnsupportedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.geteduroam.app/.
        /// </summary>
        public static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more hours.
        /// </summary>
        public static string HoursLeft {
            get {
                return ResourceManager.GetString("HoursLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string IsSure {
            get {
                return ResourceManager.GetString("IsSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is valid for.
        /// </summary>
        public static string LabelAccountValidFor {
            get {
                return ResourceManager.GetString("LabelAccountValidFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string LabelHelp {
            get {
                return ResourceManager.GetString("LabelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string LabelProfile {
            get {
                return ResourceManager.GetString("LabelProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported.
        /// </summary>
        public static string LabelSupported {
            get {
                return ResourceManager.GetString("LabelSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string LabelTermsOfUse {
            get {
                return ResourceManager.GetString("LabelTermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version.
        /// </summary>
        public static string LabelVersion {
            get {
                return ResourceManager.GetString("LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string LabelWeb {
            get {
                return ResourceManager.GetString("LabelWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more minutes.
        /// </summary>
        public static string MinutesLeft {
            get {
                return ResourceManager.GetString("MinutesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No EAP Config info to show.
        /// </summary>
        public static string NoEAPConfig {
            get {
                return ResourceManager.GetString("NoEAPConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        public static string NotSure {
            get {
                return ResourceManager.GetString("NotSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to EAP config .eap-config..
        /// </summary>
        public static string OptionDescriptionEAPConfig {
            get {
                return ResourceManager.GetString("OptionDescriptionEAPConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force action..
        /// </summary>
        public static string OptionDescriptionForce {
            get {
                return ResourceManager.GetString("OptionDescriptionForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the institute to connect to..
        /// </summary>
        public static string OptionDescriptionInstitute {
            get {
                return ResourceManager.GetString("OptionDescriptionInstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute&apos;s profile to connect to..
        /// </summary>
        public static string OptionDescriptionProfile {
            get {
                return ResourceManager.GetString("OptionDescriptionProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query to filter items.
        /// </summary>
        public static string OptionDescriptionQuery {
            get {
                return ResourceManager.GetString("OptionDescriptionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option {0} is required.
        /// </summary>
        public static string OptionRequired {
            get {
                return ResourceManager.GetString("OptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will remove all configuration for &apos;{0}&apos;..
        /// </summary>
        public static string ProfileRemoveConfirmation {
            get {
                return ResourceManager.GetString("ProfileRemoveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This means uninstalling all the trusted root certificates installed by this application..
        /// </summary>
        public static string UninstallCertificatesWarning {
            get {
                return ResourceManager.GetString("UninstallCertificatesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently in the process of completly uninstalling geteduroam.
        /// </summary>
        public static string UninstallWarning {
            get {
                return ResourceManager.GetString("UninstallWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}+Debug.
        /// </summary>
        public static string VersionDebug {
            get {
                return ResourceManager.GetString("VersionDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string VersionDebugNoVersion {
            get {
                return ResourceManager.GetString("VersionDebugNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string VersionRelease {
            get {
                return ResourceManager.GetString("VersionRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versionless.
        /// </summary>
        public static string VersionReleaseNoVersion {
            get {
                return ResourceManager.GetString("VersionReleaseNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No institutes found.
        /// </summary>
        public static string WarningNoInstitutesFound {
            get {
                return ResourceManager.GetString("WarningNoInstitutesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles found.
        /// </summary>
        public static string WarningNoProfilesFound {
            get {
                return ResourceManager.GetString("WarningNoProfilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
