<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows10.0.19041.0;netstandard2.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="EapHostUserCredentials.xsd" />
	  <None Remove="OAuthResponse.html" />
	  <None Remove="WLANProfile-v1.xsd" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DuoVia.FuzzyStrings" Version="2.1.0" />
		<PackageReference Include="ManagedNativeWifi" Version="2.5.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
		<PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
		<PackageReference Include="System.Management" Version="8.0.0" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\App.Settings\App.Settings.csproj" />
	  <ProjectReference Include="..\EduRoam.Localization\EduRoam.Localization.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="EapHostUserCredentials.xsd" />
	  <EmbeddedResource Include="OAuthResponse.html" />
	  <EmbeddedResource Include="WLANProfile-v1.xsd" />
	</ItemGroup>

</Project>
