//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRoam.Connect {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduRoam.Connect.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is valid for.
        /// </summary>
        public static string AccountValidFor {
            get {
                return ResourceManager.GetString("AccountValidFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more days.
        /// </summary>
        public static string DaysLeft {
            get {
                return ResourceManager.GetString("DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more hours.
        /// </summary>
        public static string HoursLeft {
            get {
                return ResourceManager.GetString("HoursLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more minutes.
        /// </summary>
        public static string MinutesLeft {
            get {
                return ResourceManager.GetString("MinutesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}+Debug.
        /// </summary>
        public static string VersionDebug {
            get {
                return ResourceManager.GetString("VersionDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string VersionDebugNoVersion {
            get {
                return ResourceManager.GetString("VersionDebugNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version.
        /// </summary>
        public static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string VersionRelease {
            get {
                return ResourceManager.GetString("VersionRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versionless.
        /// </summary>
        public static string VersionReleaseNoVersion {
            get {
                return ResourceManager.GetString("VersionReleaseNoVersion", resourceCulture);
            }
        }
    }
}
