<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Govroam.App</RootNamespace>
    <AssemblyName>getgovroam</AssemblyName>
    <StartupObject>Govroam.App.App</StartupObject>
    <ApplicationIcon>getgovroam.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RuntimeIdentifiers>win-arm64;win-x64</RuntimeIdentifiers>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\App.Library\App.Library.csproj" />
    <ProjectReference Include="..\App.Settings\App.Settings.csproj" />
    <ProjectReference Include="..\EduRoam.Localization\EduRoam.Localization.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="application-icon.png" />
    <Resource Include="logo.png" />
    <EmbeddedResource Include="logo-light.svg" />
    <Content Include="getgovroam.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
