//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Library.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Library.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eduroam.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string ButtonPrevious {
            get {
                return ResourceManager.GetString("ButtonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to certificates are installed.
        /// </summary>
        internal static string CertificateTitleInstalled {
            get {
                return ResourceManager.GetString("CertificateTitleInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to continue you have to install the listed certificates.
        /// </summary>
        internal static string CertificateTitleStart {
            get {
                return ResourceManager.GetString("CertificateTitleStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to eduroam.
        /// </summary>
        internal static string ConnectToEduroam {
            get {
                return ResourceManager.GetString("ConnectToEduroam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        internal static string ProfileContactInfo {
            get {
                return ResourceManager.GetString("ProfileContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ProfileEmail {
            get {
                return ResourceManager.GetString("ProfileEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not affiliated with institution?.
        /// </summary>
        internal static string ProfileNotAffiliatedInstitution {
            get {
                return ResourceManager.GetString("ProfileNotAffiliatedInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string ProfilePhone {
            get {
                return ResourceManager.GetString("ProfilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select other institution.
        /// </summary>
        internal static string ProfileSelectOtherInstitution {
            get {
                return ResourceManager.GetString("ProfileSelectOtherInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string ProfileWeb {
            get {
                return ResourceManager.GetString("ProfileWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to be redirected to the insitutions site for more info on how to connect. When you click the link this application will close..
        /// </summary>
        internal static string RedirectText {
            get {
                return ResourceManager.GetString("RedirectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect.
        /// </summary>
        internal static string RedirectTitle {
            get {
                return ResourceManager.GetString("RedirectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select institution.
        /// </summary>
        internal static string SelectInstitution {
            get {
                return ResourceManager.GetString("SelectInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select profile.
        /// </summary>
        internal static string SelectProfile {
            get {
                return ResourceManager.GetString("SelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        internal static string TermsOfUseTitle {
            get {
                return ResourceManager.GetString("TermsOfUseTitle", resourceCulture);
            }
        }
    }
}
